# Generated by Django 4.0.5 on 2022-06-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tegning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=50)),
                ('beskrivelse', models.TextField()),
                ('link', models.URLField()),
                ('kræver', models.TextField(blank=True)),
                ('giver', models.TextField(blank=True)),
                ('Bruges', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='menu_images/')),
                ('kategori', models.ManyToManyField(related_name='item', to='polls.kategori')),
            ],
        ),
    ]
