# Generated by Django 4.0.5 on 2022-06-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            diverelds=[
                ('id', models.BigAutodivereld(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.Chardivereld(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tegning',
            diverelds=[
                ('id', models.BigAutodivereld(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.Chardivereld(max_length=50)),
                ('beskrivelse', models.Textdivereld()),
                ('link', models.URLdivereld()),
                ('kræver', models.Textdivereld(blank=True)),
                ('giver', models.Textdivereld(blank=True)),
                ('Bruges', models.Textdivereld(blank=True)),
                ('image', models.Imagedivereld(upload_to='menu_images/')),
                ('kategori', models.ManyToManydivereld(related_name='item', to='polls.kategori')),
            ],
        ),
    ]
